In [ ]:
import numpy as np

In [ ]:
# Q1

Q1 = np.array([[1,2],[3,4]])
print (Q1)

[[1 2]
 [3 4]]


In [ ]:
# Q2

Q2 = np.random.randint(low=0, high=10, size=(3, 4))
print (Q2)

[[1 9 3 1]
 [3 7 0 3]
 [8 3 5 3]]


In [ ]:
# Q3

Q3A = np.zeros((1, 2))
Q3B = np.ones((1, 2))

print (Q3A, "\n", Q3B)

[[0. 0.]] 
 [[1. 1.]]


In [ ]:
# Q4

Q4 = np.random.randint(low=0, high=10, size=(6, 3))

print (Q4, "\n\n", Q4.T)

[[2 3 4]
 [6 1 7]
 [6 8 9]
 [9 5 1]
 [9 8 0]
 [4 3 6]] 

 [[2 6 6 9 9 4]
 [3 1 8 5 8 3]
 [4 7 9 1 0 6]]


In [29]:
# Q5


m, n, p = 4, 2, 2
Q5A = np.random.randint(0, 10, (n, p))
Q5B = np.random.randint(0, 10, (p, m))

dotResult = np.dot(Q5A, Q5B)
print ("Array A : \n\n", Q5A, "\n\n", "Array B : \n\n", Q5B, "\n\n", "Dot results : \n\n", dotResult)



Array A : 

 [[2 6]
 [3 5]] 

 Array B : 

 [[2 0 8 8]
 [7 3 7 5]] 

 Dot results : 

 [[46 18 58 46]
 [41 15 59 49]]
